version: '3'

tasks:
  # ────────────────────────────────────────
  # ヘルプ
  # ────────────────────────────────────────
  default:
    desc: クイックガイド
    cmds:
      - |
          cat <<'EOF'
          ■ セットアップ（初回のみ）
            task setup

          ■ 開発・実行
            task dev                      ローカル実行
            task up                       systemd起動
            task down                     systemd停止
            task restart                  systemd再起動
            task status                   全体状態確認
            task logs                     ログ追尾

          ■ 録音・処理（メイン機能）
            task record                   手動録音
            task process FILE=録音.wav    1ファイル処理
            task process:all              全録音を一括処理

          ■ Windows 起動（確実な経路）
            PowerShell:    .\\run.ps1
            CMD:           run.cmd
            ダブルクリック: run.cmd
            WSL bash→Win:  WINPWD=$(wslpath -w "$PWD"); powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$WINPWD\\run.ps1"
          ■ bootstrap（管理者PowerShell）
            powershell -NoProfile -ExecutionPolicy Bypass -File "\\wsl.localhost\\Ubuntu-22.04\\home\\kafka\\projects\\vlog\\bootstrap.ps1"
          ■ bootstrap テスト（WSL→Windows / スケジュール登録なし）
            WINPWD=$(wslpath -w "$PWD"); powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$WINPWD\\bootstrap.ps1" -NoSchedule
          ■ bootstrap テスト（WSL→Windows / 予約なし）
            WINPWD=$(wslpath -w "$PWD"); powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$WINPWD\\bootstrap.ps1" -NoSchedule

          ■ データ同期
            task sync                     Supabase同期
            task sync:full                全件強制同期

          ■ Web UI
            task web:dev                  開発サーバー
            task web:build                本番ビルド
            task web:deploy               Vercelデプロイ

          ■ メンテナンス
            task lint                     コード品質チェック
            task clean                    キャッシュ削除
            task commit MESSAGE="..."     Git commit

          ■ デバッグ用
            task service:status           systemd状態のみ
            task log:status               ログ解析のみ
            task transcribe FILE=...      文字起こしのみ
            task summarize FILE=...       要約のみ
          EOF

  # ────────────────────────────────────────
  # セットアップ
  # ────────────────────────────────────────
  setup:
    desc: 依存同期
    cmd: uv sync

  # ────────────────────────────────────────
  # 開発・実行
  # ────────────────────────────────────────
  dev:
    desc: アプリ実行
    cmd: uv run python -m src.main

  up:
    desc: systemd起動
    cmd: systemctl --user enable --now "$(pwd)/vlog.service"

  down:
    desc: systemd停止
    cmd: systemctl --user disable --now vlog.service

  restart:
    desc: systemd再起動
    cmd: systemctl --user restart vlog

  status:
    desc: 全体状態確認（service + log）
    cmds:
      - echo "■ systemd 状態"
      - systemctl --user status vlog --no-pager --lines=10 || true
      - echo ""
      - echo "■ ログ解析"
      - python3 view_logs.py

  logs:
    desc: ログ追尾（リアルタイム）
    cmd: journalctl --user -u vlog -f

  # ────────────────────────────────────────
  # 録音・処理
  # ────────────────────────────────────────
  record:
    desc: 手動録音開始
    cmd: uv run python -m src.cli record

  process:
    desc: 録音→要約（単一ファイル）
    deps: [require_file]
    cmds: ["uv run python -m src.cli process --file {{.FILE}}"]

  process:all:
    desc: 録音→要約（全ファイル一括）
    cmds:
      - for f in recordings/*.wav recordings/*.flac; do [ -f "$f" ] && task process FILE="$f"; done || true

  transcribe:all:
    desc: 文字起こしのみ（全ファイル）
    cmds:
      - for f in recordings/*.wav recordings/*.flac; do [ -f "$f" ] && task transcribe FILE="$f"; done || true

  # ────────────────────────────────────────
  # データ同期
  # ────────────────────────────────────────
  sync:
    desc: Supabase同期
    cmd: uv run python src/sync_supabase.py

  sync:full:
    desc: 全件強制同期
    cmds:
      - touch summaries/*.txt
      - task sync

  # ────────────────────────────────────────
  # Windows bootstrap
  # ────────────────────────────────────────
  bootstrap:
    desc: Windows 自動起動セットアップ（管理者PowerShellで実行）
    cmd: powershell -NoProfile -ExecutionPolicy Bypass -File "\\wsl.localhost\\Ubuntu-22.04\\home\\kafka\\projects\\vlog\\bootstrap.ps1"

  bootstrap:test:
    desc: WSL→Windows でスケジュール登録なしの動作確認
    cmd: WINPWD=$(wslpath -w "$PWD"); powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$WINPWD\\bootstrap.ps1" -NoSchedule

  # ────────────────────────────────────────
  # Web UI
  # ────────────────────────────────────────
  web:dev:
    desc: 開発サーバー
    cmd: cd frontend/reader && npm run dev -- --hostname 0.0.0.0 --port 3000

  web:build:
    desc: ビルド
    cmd: cd frontend/reader && npm run build

  web:start:
    desc: 本番起動（ポート4000）
    cmd: cd frontend/reader && npm run start -- --hostname 0.0.0.0 --port 4000

  web:deploy:
    desc: Vercelデプロイ
    cmds:
      - cd frontend/reader && npx vercel link --project kaflog --yes
      - cd frontend/reader && npx vercel --prod --yes

  web:env:
    desc: 環境変数抽出
    cmds:
      - test -f .env || (echo ".env がありません" && exit 1)
      - |
        . ./.env
        cat >frontend/reader/.env.local <<EOF
        NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        EOF

  # ────────────────────────────────────────
  # メンテナンス
  # ────────────────────────────────────────
  lint:
    desc: コード品質チェック
    cmds: ["uv run ruff check src && uv run ruff format src"]

  clean:
    desc: キャッシュ削除
    cmds: ["rm -rf __pycache__ .ruff_cache && find . -type d -name __pycache__ -exec rm -rf {} + || true"]

  commit:
    desc: Git commit
    cmds: ["git add . && git commit -am '{{.MESSAGE}}'"]

  # ────────────────────────────────────────
  # デバッグ用
  # ────────────────────────────────────────
  service:status:
    desc: systemd状態のみ
    cmd: systemctl --user status vlog

  log:status:
    desc: ログ解析のみ
    cmd: python3 view_logs.py

  transcribe:
    desc: 文字起こしのみ
    deps: [require_file]
    cmds: ["uv run python -m src.cli transcribe --file {{.FILE}}"]

  summarize:
    desc: 要約のみ
    deps: [require_file]
    cmds: ["uv run python -m src.cli summarize --file {{.FILE}}"]

  # ────────────────────────────────────────
  # 内部ヘルパー
  # ────────────────────────────────────────
  require_file:
    internal: true
    preconditions:
      - sh: test -n "{{.FILE}}"
        msg: FILEを指定してください
