version: '3'
tasks:
  default:
    desc: ユーザーストーリー別クイックガイド
    cmds:
      - |
          cat <<'EOF'
          [セットアップ] task setup
          [開発実行]     task dev
          [サービス]     task up | task down | task status | task logs | task restart
          [録音/処理]    task record | task process FILE=... | task transcribe FILE=... | task summarize FILE=...
          [品質]         task lint
          [後片付け]     task clean
          [コミット]     task commit MESSAGE="説明"
          EOF

  setup:
    desc: 依存同期 (uv sync)
    cmd: uv sync

  dev:
    desc: アプリをフォアグラウンド実行
    cmd: uv run python -m src.main

  up:
    desc: systemdユーザーサービスを有効化して起動
    cmd: systemctl --user enable --now vlog.service

  down:
    desc: systemdユーザーサービスを無効化して停止
    cmd: systemctl --user disable --now vlog.service

  status:
    desc: systemdユーザーサービスの状態表示
    cmd: systemctl --user status vlog

  logs:
    desc: systemdユーザーサービスのログ追尾
    cmd: journalctl --user -u vlog -f

  restart:
    desc: systemdユーザーサービスを再起動
    cmd: systemctl --user restart vlog

  record:
    desc: 手動録音を開始 (Ctrl+Cで停止)
    cmd: uv run python -m src.cli record

  process:
    desc: 録音ファイル一括処理 (Transcribe→Summarize) FILE=path/to/audio.wav
    cmds:
      - test -n "{{.FILE}}" || (echo "FILEを指定してください" && exit 1)
      - uv run python -m src.cli process --file {{.FILE}}

  transcribe:
    desc: 音声→テキスト変換 (FILE=path/to/audio.wav)
    cmds:
      - test -n "{{.FILE}}" || (echo "FILEを指定してください" && exit 1)
      - uv run python -m src.cli transcribe --file {{.FILE}}

  summarize:
    desc: テキスト要約 (FILE=path/to/text.txt)
    cmds:
      - test -n "{{.FILE}}" || (echo "FILEを指定してください" && exit 1)
      - uv run python -m src.cli summarize --file {{.FILE}}

  lint:
    desc: Ruffで静的解析＋フォーマット
    cmds:
      - uv run ruff check src
      - uv run ruff format src

  clean:
    desc: キャッシュ類を削除 (__pycache__/.ruff_cache)
    cmds:
      - rm -rf __pycache__ .ruff_cache
      - find . -type d -name "__pycache__" -exec rm -rf {} + || true

  commit:
    desc: Git add && commit
    cmds:
      - git add .
      - git commit -am "{{.MESSAGE}}"
