version: '3'

tasks:
  default:
    desc: クイックガイド
    cmds:
      - |
          cat <<'EOF'
          [セットアップ] task setup
          [開発実行]     task dev
          [サービス]     task up | task down | task status | task logs | task restart
          [ログ確認]     task log:status
          [録音/処理]    task record | task process FILE=... | task process:all
          [品質]         task lint
          [同期]         task sync | task sync:force
          [後片付け]     task clean
          [コミット]     task commit MESSAGE="説明"
          EOF

  setup: {desc: 依存同期, cmd: uv sync}
  dev:   {desc: アプリ実行, cmd: uv run python -m src.main}

  up:      {desc: systemd有効化+起動, cmd: systemctl --user enable --now "$(pwd)/vlog.service"}
  down:    {desc: systemd無効化+停止, cmd: systemctl --user disable --now vlog.service}
  status:  {desc: systemd状態, cmd: systemctl --user status vlog}
  logs:    {desc: systemdログ追尾, cmd: journalctl --user -u vlog -f}
  restart: {desc: systemd再起動, cmd: systemctl --user restart vlog}

  log:status: {desc: ログ状態確認, cmd: python3 view_logs.py}

  reader:dev:    {desc: frontend/reader dev, cmd: cd frontend/reader && npm run dev -- --hostname 0.0.0.0 --port 3000}
  reader:build:  {desc: frontend/reader build, cmd: cd frontend/reader && npm run build}
  reader:start:  {desc: frontend/reader prod(4000), cmd: cd frontend/reader && npm run start -- --hostname 0.0.0.0 --port 4000}
  reader:deploy:
    desc: frontend/reader デプロイ
    cmds:
      - cd frontend/reader && npx vercel link --project kaflog --yes
      - cd frontend/reader && npx vercel --prod --yes
  reader:env:
    desc: ./.env → frontend/reader/.env.local に抽出
    cmds:
      - test -f .env || (echo ".env がありません" && exit 1)
      - |
        . ./.env
        cat >frontend/reader/.env.local <<EOF
        NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        EOF

  record:    {desc: 手動録音開始, cmd: uv run python -m src.cli record}

  process:
    desc: 録音→要約 (単一ファイル)
    deps: [require_file]
    cmds: ["uv run python -m src.cli process --file {{.FILE}}"]

  process:all:
    desc: 録音→要約 (全ファイル一括)
    cmds:
      - for f in recordings/*.wav recordings/*.flac; do [ -f "$f" ] && task process FILE="$f"; done || true

  transcribe:
    desc: 音声→テキスト
    deps: [require_file]
    cmds: ["uv run python -m src.cli transcribe --file {{.FILE}}"]

  summarize:
    desc: テキスト要約
    deps: [require_file]
    cmds: ["uv run python -m src.cli summarize --file {{.FILE}}"]

  sync: {desc: summaries を Supabase 同期, cmd: uv run python src/sync_supabase.py}

  sync:force:
    desc: 全件強制同期 (touch & sync)
    cmds:
      - touch summaries/*.txt
      - task sync

  lint:
    desc: Ruff check+format
    cmds: ["uv run ruff check src && uv run ruff format src"]

  clean:
    desc: キャッシュ削除
    cmds: ["rm -rf __pycache__ .ruff_cache && find . -type d -name __pycache__ -exec rm -rf {} + || true"]

  commit:
    desc: Git add+commit
    cmds: ["git add . && git commit -am '{{.MESSAGE}}'"]

  require_file:
    internal: true
    preconditions:
      - sh: test -n "{{.FILE}}"
        msg: FILEを指定してください
