version: "3"

env: {}

tasks:
  # ────────────────────────────────────────
  # ヘルプ
  # ────────────────────────────────────────
  default:
    desc: クイックガイド
    cmds:
      - |
        cat <<'EOF'
        ■ 開発・実行 (Rust 優先)
          task dev                      ローカル監視 (Rust)
          task process FILE=録音.wav    1ファイル処理 (Rust)
          task sync                     データ同期 (Rust)
          task up                       systemd起動

        ■ コンテンツ生成
          task novel:build              今日の要約から章を生成
          task photo novel=...          小説から画像生成
          task photos:fill              欠落画像を自動補完

        ■ メンテナンス & 品質管理
          task lint                     Rust品質チェック
          task commit MESSAGE="..."     Git commit
          task clean                    キャッシュ削除

        ■ デバッグ・詳細
          task rust:dev                 デバッグ実行 (cargo run)
          task service:status           systemd状態確認
        EOF

  # ────────────────────────────────────────
  # セットアップ
  # ────────────────────────────────────────
  setup:
    desc: 対話セットアップ (Rust)
    cmd: cargo run -- setup

  # ────────────────────────────────────────
  # 開発・実行 (Rust Core)
  # ────────────────────────────────────────
  dev:
    desc: ローカル監視 (Rust)
    cmd: cargo run -- monitor

  rust:dev:
    desc: アプリ実行 (Rust)
    cmd: cargo run

  rust:build:
    desc: ビルド (Rust)
    cmd: cargo build --release

  rust:monitor:
    desc: 監視モード (Rust)
    cmd: cargo run --release -- monitor

  windows:run:
    desc: Windows Rust monitor起動 (WSL経由)
    cmd: /mnt/c/Windows/System32/cmd.exe /c windows\\run.bat

  # ────────────────────────────────────────
  # Systemd Control
  # ────────────────────────────────────────
  up:
    desc: systemd起動
    cmds:
      - systemctl --user enable --now "$(pwd)/vlog.service"
      - systemctl --user link "$(pwd)/vlog-daily.service" || true
      - systemctl --user enable --now "$(pwd)/vlog-daily.timer"

  down:
    desc: systemd停止
    cmds:
      - systemctl --user disable --now vlog.service
      - systemctl --user disable --now vlog-daily.timer

  restart:
    desc: systemd再起動
    cmd: systemctl --user restart vlog

  status:
    desc: 全体状態確認
    cmds:
      - cargo run -- status

  logs:
    desc: ログ追尾
    cmd: journalctl --user -u vlog -f

  # ────────────────────────────────────────
  # 処理 (Rust)
  # ────────────────────────────────────────
  process:
    desc: 録音→要約（Rust）
    cmds: ["cargo run -- process --file {{.FILE}}"]
    preconditions:
      - sh: test -n "{{.FILE}}"
        msg: FILE=...を指定してください

  process:all:
    desc: 録音→要約（全ファイル一括）
    cmds:
      - for f in data/recordings/*.wav data/recordings/*.flac; do [ -f "$f" ] && task process FILE="$f"; done || true

  process:today:
    desc: 今日の録音を一括処理
    cmds:
      - |
        TODAY=$(date +%Y%m%d)
        rm -f data/summaries/${TODAY}_summary.txt
        for f in data/recordings/${TODAY}*.wav data/recordings/${TODAY}*.flac; do
          [ -f "$f" ] && task process FILE="$f"
        done || true

  process:yesterday:
    desc: 昨日の録音を一括処理
    cmds:
      - |
        YESTERDAY=$(date -d "yesterday" +%Y%m%d)
        rm -f data/summaries/${YESTERDAY}_summary.txt
        for f in data/recordings/${YESTERDAY}*.wav data/recordings/${YESTERDAY}*.flac; do
          [ -f "$f" ] && task process FILE="$f"
        done || true

  process:daily:
    desc: 日次処理（昨日＋今日）
    cmds:
      - task process:yesterday
      - task process:today
      - YESTERDAY=$(date -d "yesterday" +%Y%m%d); task novel:build date=$YESTERDAY || true
      - TODAY=$(date +%Y%m%d); task novel:build date=$TODAY || true
      - task photos:fill
      - YESTERDAY=$(date -d "yesterday" +%Y%m%d); task curator:eval date=$YESTERDAY || true

  curator:eval:
    desc: コンテンツ評価 (Rust)
    cmds:
      - cargo run -- evaluate --date {{.date}}

  # ────────────────────────────────────────
  # データ同期 (Rust)
  # ────────────────────────────────────────
  sync:
    desc: Supabase同期 (Rust)
    cmd: cargo run --release -- sync

  sync:full:
    desc: 全件強制同期
    cmds:
      - touch data/summaries/*.txt
      - task sync

  # ────────────────────────────────────────
  # Web UI
  # ────────────────────────────────────────
  web:dev:
    desc: 開発サーバー
    cmd: cd frontend/reader && npm run dev -- --hostname 0.0.0.0 --port 3000

  web:build:
    desc: ビルド
    cmd: cd frontend/reader && npm run build

  web:start:
    desc: 本番起動
    cmd: cd frontend/reader && npm run start -- --hostname 0.0.0.0 --port 4000

  web:deploy:
    desc: Vercelデプロイ
    cmds:
      - cd frontend/reader && npx vercel link --project kaflog --yes
      - cd frontend/reader && npx vercel --prod --yes

  web:env:
    desc: 環境変数抽出
    cmds:
      - test -f .env || (echo ".env がありません" && exit 1)
      - |
        . ./.env
        cat >frontend/reader/.env.local <<EOF
        NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        EOF

  # ────────────────────────────────────────
  # メンテナンス
  # ────────────────────────────────────────
  lint:
    desc: コード品質チェック
    cmds:
      - cargo clippy --fix --allow-dirty --allow-staged
      - cargo fmt

  clean:
    desc: キャッシュ削除
    cmds:
      [
        "rm -rf __pycache__ .ruff_cache && find . -type d -name __pycache__ -exec rm -rf {} + || true",
      ]

  commit:
    desc: Git commit
    cmds: ["git add . && git commit -am '{{.MESSAGE}}'"]

  test:
    desc: Rustユニットテスト
    cmd: cargo test

  windows:build:
    desc: Windowsエージェントビルド
    cmd: cd src/windows/agent && cargo build --release --target x86_64-pc-windows-msvc

  # ────────────────────────────────────────
  # デバッグ用
  # ────────────────────────────────────────
  service:status:
    desc: systemd状態のみ
    cmd: systemctl --user status vlog

  # ────────────────────────────────────────
  # 小説・画像 (Python/Rust Hybrid)
  # ────────────────────────────────────────
  novel:build:
    desc: 小説の章を生成 (Rust)
    cmds:
      - cargo run -- novel {{if .date}}--date {{.date}}{{end}}

  photo:
    desc: 小説から画像を生成 (Python)
    cmds:
      - uv run python src/scripts/image_gen.py --prompt "$(cat {{.novel}})" --output data/photos/$(basename {{.novel}} .md).png
    preconditions:
      - sh: test -n "{{.novel}}"
        msg: novel=data/novels/YYYYMMDD.mdを指定してください

  photos:
    desc: 全小説から画像を一括生成
    cmds:
      - for f in data/novels/*.md; do [ -f "$f" ] && task photo novel="$f"; done || true
