version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  run:
    desc: Run the VRChat Auto-Diary application
    cmd: uv run python -m src.main

  test:
    desc: Run tests
    cmd: uv run pytest tests -v

  format:
    desc: Format code with ruff
    cmd: uv run ruff format src tests

  lint:
    desc: Lint code with ruff
    cmd: uv run ruff check src tests

  check:
    desc: Run both format and lint
    cmds:
      - task: format
      - task: lint

  sync:
    desc: Sync dependencies
    cmd: uv sync

  service:enable:
    desc: Enable and start systemd service
    cmd: systemctl --user enable --now vlog.service

  service:disable:
    desc: Disable and stop systemd service
    cmd: systemctl --user disable --now vlog.service

  service:status:
    desc: Check systemd service status
    cmd: systemctl --user status vlog

  service:logs:
    desc: View systemd service logs
    cmd: journalctl --user -u vlog -f

  service:restart:
    desc: Restart systemd service
    cmd: systemctl --user restart vlog

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf __pycache__ .pytest_cache .ruff_cache
      - find . -type d -name "__pycache__" -exec rm -rf {} + || true
